### ISSUE TITLE
dom.js 404

### ISSUE THREAD

**Issue by constantx** [mikesall/charted#100]
I cloned and run `npm install && npm start` locally, the server run fine, but when I add a URL to load data, the page just refresh and not load anything.

See this in the console.
<img width="953" alt="developer_tools_-_http___localhost_5000__dataurl_https_3a_2f_2fwww_dropbox_com_2fs_2f7kca5ih3d2l2alb_2fchopp_vn-metrics-v2_2520-_2520_255bcharted_255d_csv_3fdl_3d0" src="https://cloud.githubusercontent.com/assets/113969/23091572/ce9ecba2-f5eb-11e6-9ce0-12a4e7dedfff.png">

**Comment by valueof** [comment]
Can you sync with master and try again? Current master has some issues I'm working on (see the TODO file) so maybe it would be better to check out the latest release commit?

**Comment by constantx** [comment]
will do.
