### ISSUE TITLE
Move the options into the hash

### ISSUE THREAD

**Issue by rgrochowicz** [mikesall/charted#43]
As it stands now, the options are stored in the query, and those options are sent to the server when the chart is accessed directly. If the options were moved to the hash, not only would some bandwidth be saved, but also the whole website could be cached client side (except for /get). No server-side processing is done to the options, so this seems like a safe change.

For example:
This `http://www.charted.co/?%7B%7D` would turn into this `http://www.charted.co/#%7B%7D`

**Comment by valueof** [comment]
Closing. We load URLs through the server.
