### ISSUE TITLE
error running npm install locally

### ISSUE THREAD

**Issue by mikesall** [mikesall/charted#65]
The error output looks like this:
<img width="508" alt="screen shot 2015-12-24 at 11 40 20 pm" src="https://cloud.githubusercontent.com/assets/676030/11999937/20249a6a-aa98-11e5-9e58-d9d3243a07a4.png">

**Comment by valueof** [comment]
You have a very old version of Node. You should update to 4.x.

Anton

**Comment by mikesall** [comment]
😳
