### ISSUE TITLE
No longer reading Shared Google sheet

### ISSUE THREAD

**Issue by DimitriStrutt** [mikesall/charted#77]
Since the 15th of February charts which had been working for about a year have suddenly ceased to display anything meaningful; behaving as if the Google sheets were not public.

I have created a new one: https://docs.google.com/spreadsheets/d/1i5INeh718Hj2AiKbiRq5eRL5qiekHR9Lzvs4NjCNmtc/edit?usp=sharing

which cannot be read correctly. Has some update messed things up?

Dimitri

**Comment by valueof** [comment]
Hm, that's weird. Thanks, I'll look into this soon.

**Comment by DimitriStrutt** [comment]
Thanks, I'm pretty sure I changed nothing in Google Drive. Is it only
happening to me though?
Regards

Dimitri

*Dimitri Strutt*

*Webinfinity Europe Limited*

Personalize every experience

*T:* +44 (0)1737 225 130 | *W:* www.webinfinity.com

Webinfinity Europe Limited is a company registered in England and Wales.
Company Reg. No.3843393. Registered Office: 3 Holmesdale House, 46 Croydon
Road, Reigate, RH2 0NH

**Comment by valueof** [comment]
I can reproduce it as well but we work on Charted in our spare time so it'll take a little bit until I can do another release—this weekend most likely.

**Comment by valueof** [comment]
Thanks for the bug report, Dimitri. I've fixed the issue here and will deploy it to charted.co shortly. When I was rewriting our URL parses to use Node's `url` library I misunderstood their API which resulted in Charted requesting and trying to parse `.xlsx` instead of `.csv`.

**Comment by valueof** [comment]
Here we go: http://www.charted.co/c/dd8c2a8
