### ISSUE TITLE
dropbox link to CSV file doesnt work

### ISSUE THREAD

**Issue by constantx** [mikesall/charted#80]
<img width="458" alt="chopp_vn_-_dropbox" src="https://cloud.githubusercontent.com/assets/113969/15289634/bea43058-1b9d-11e6-9230-633461034c22.png">

Using a dropbox link with permission set to "Anyone with the link can see it" but charted rendered some html: 

<img width="525" alt="__doctype_html__html_lang__en__xmlns_fb__http___ogp_me_ns_fb___xml_lang__en__class__media-desktop__xmlns__http___www_w3_org_1999_xhtml___head__script_nonce__imsyqcryyiipktq5zjlw__" src="https://cloud.githubusercontent.com/assets/113969/15289648/dfd34070-1b9d-11e6-8898-f4c57096a0c0.png">

**Comment by valueof** [comment]
Is there an example link you can give us? Seems like Dropbox is returning HTML instead of CSV? (Although we should handle this case more gracefully)

**Comment by constantx** [comment]
here's a sample link: https://www.dropbox.com/s/pbrtd50jpwlx5n8/charted-sample.csv?dl=0

**Comment by kdodia** [comment]
By default Dropbox's sharing link points to a webpage for that file. You can get direct access by changing the query in the URL to `?dl=1`, i.e. https://www.dropbox.com/s/pbrtd50jpwlx5n8/charted-sample.csv?dl=1.

It would be cool if charted.co handled that gracefully.
