### ISSUE TITLE
Loading a short url should populate the input while it fetches the data

### ISSUE THREAD

**Issue by mikesall** [mikesall/charted#88]
Currently, when going to a short url, it shows the spinner while it's fetching the data, but the input field remains empty. Instead, the input field should be immediately populated with the full url while it's fetching the data. This is especially helpful when it takes a while to get the data, so that you can still see what url it's using.

**Comment by mikesall** [comment]
😱🎉 this is the best thank you!

**Comment by valueof** [comment]
It's not on charted.co yet—will put it out there tonight.
